export const metadata = {
  title: "Terms of Service — Marketworks",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-12 prose prose-neutral dark:prose-invert">
      <h1>Terms of Service</h1>

      <div className="rounded-md border border-amber-300/40 bg-amber-50 p-4 text-sm dark:bg-amber-950/30 not-prose">
        <p className="m-0 font-medium">
          Marketworks is in <strong>Private Beta</strong>. SEBI Research
          Analyst registration is currently applied for. The platform is
          made available for testing, research, and educational purposes
          only — nothing on this site is investment advice.
        </p>
      </div>

      <h2>Acceptance</h2>
      <p>
        By creating an account or accessing the Marketworks dashboard
        during the beta, you agree to these terms. If you do not agree,
        do not use the service.
      </p>

      <h2>Eligibility</h2>
      <p>
        You must be at least 18 years old and a resident of India eligible
        to invest in Indian equities. Beta access is invite-only and
        provided at our discretion.
      </p>

      <h2>What we provide</h2>
      <p>
        Read-only access to model portfolios, performance data, rebalance
        signals, and trade history generated by Marketworks&apos;
        quantitative strategies. We do not place trades or hold customer
        funds. Outputs are not personalised; they are not investment
        advice.
      </p>

      <h2>Data accuracy</h2>
      <p>
        We work to keep portfolio and price data accurate but make no
        warranty as to completeness or timeliness. Data is sourced from
        third-party providers (Zerodha KiteConnect and others) and may be
        subject to delays or outages.
      </p>

      <h2>Account use</h2>
      <p>
        You are responsible for keeping your sign-in credentials secure
        and for all activity under your account. You may not share your
        account with others or attempt to access the platform&apos;s
        administrative surfaces.
      </p>

      <h2>Termination</h2>
      <p>
        We may suspend or terminate beta access at our discretion or in
        response to violations. You may delete your account at any time
        from the Account page.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the maximum extent permitted by Indian law, Marketworks is not
        liable for indirect, incidental, or consequential damages arising
        from your use of the platform — including investment losses.
      </p>

      <h2>Changes</h2>
      <p>
        These terms may be updated from time to time. Material changes
        will be communicated through the dashboard.
      </p>
    </div>
  );
}
