"""Run the 5 retune candidates through the LEGACY engine
(`build_momentum_signals_flexible.py` + `backtest_momentum.py`) on the
production data window (nse500_data, 2020+).

Purpose: get apples-to-apples comparison vs the CLAUDE.md production
claim (59.4% CAGR / 1.92 Sharpe / -30.0% DD), which was generated by
this same legacy engine. The new `_momentum_engine.py` produced ~10pp
lower CAGR for the same config; this script tells us if the retune
winners' edge over production also shows up in the legacy engine.

Output: tasks/MM-tuning/legacy_compare.csv
"""
from __future__ import annotations

import argparse
import math
import subprocess
import sys
import tempfile
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]


# 5 configs: production + 4 OOS winners
# Each: (label, lookback_months, skip_days, vol_floor, vol_power, exit_buffer)
# Other params held constant: top_n=24, min_hold_days=8, rebalance_weeks=1, scenario=baseline,
# slippage=0.002, score_rebalance_mode=incremental, universe=NSE 500.
CONFIGS = [
    ("PRODUCTION (current)", 6, 0, 0.05, 1.0, 0),
    ("A2_b0 (L6 vf05 skip5 buf0)", 6, 5, 0.05, 1.0, 0),
    ("A2_b6 (L6 vf05 skip5 buf6)", 6, 5, 0.05, 1.0, 6),
    ("B1_b6 (L9 vf01 vp.5 buf6)", 9, 5, 0.01, 0.5, 6),
    ("B2_b6 (L9 vf05 buf6)",      9, 5, 0.05, 1.0, 6),
]


def run_cmd(cmd, quiet=True):
    """Run a subprocess; raise on failure."""
    if quiet:
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode != 0:
            print(f"FAILED: {' '.join(str(c) for c in cmd)}", file=sys.stderr)
            print(r.stdout)
            print(r.stderr, file=sys.stderr)
            raise SystemExit(r.returncode)
        return r.stdout
    else:
        return subprocess.run(cmd).returncode


def run_one(label, lb, skip, vf, vp, buf, prices_dir, universe_file, work_dir):
    """Build signals + run legacy backtest. Return metrics dict."""
    signals_path = work_dir / f"signals_{label.split()[0]}.csv"
    bt_dir = work_dir / f"bt_{label.split()[0]}"
    bt_dir.mkdir(parents=True, exist_ok=True)

    # 1. Build signals — request top_n + buf so the backtest's exit-buffer
    # logic has ranks 25-30 to consult. Without this, exit_buffer is a no-op.
    sig_top_n = 24 + buf
    sig_cmd = [
        sys.executable, "scripts/build_momentum_signals_flexible.py",
        "--prices-dir", str(prices_dir),
        "--output", str(signals_path),
        "--lookback-months", str(lb),
        "--skip-days", str(skip),
        "--top-n", str(sig_top_n),
        "--vol-floor", str(vf),
        "--vol-power", str(vp),
        "--universe-file", str(universe_file),
        "--rebalance-weeks", "1",
    ]
    print(f"  [signals] lb={lb} skip={skip} vf={vf} vp={vp} ...", flush=True)
    run_cmd(sig_cmd)

    # 2. Backtest
    bt_cmd = [
        sys.executable, "scripts/backtest_momentum.py",
        "--prices-dir", str(prices_dir),
        "--signals", str(signals_path),
        "--benchmark", str(ROOT / "data/benchmarks/nifty100.csv"),
        "--output-dir", str(bt_dir),
        "--top-n", "24",
        "--slippage", "0.002",
        "--scenario", "baseline",
        "--exit-buffer", str(buf),
        "--min-hold-days", "8",
        "--score-rebalance-mode", "incremental",
    ]
    print(f"  [backtest] buf={buf} min_hold=8 ...", flush=True)
    run_cmd(bt_cmd)

    # 3. Read metrics
    metrics_path = bt_dir / "momentum_metrics.csv"
    if not metrics_path.exists():
        raise RuntimeError(f"metrics not produced for {label}")
    m = pd.read_csv(metrics_path).iloc[0].to_dict()

    # Legacy backtest_momentum.py doesn't compute Sharpe/vol/Sortino —
    # we compute them from the equity curve here so we can compare to
    # CLAUDE.md's claimed Sharpe.
    eq = pd.read_csv(bt_dir / "momentum_equity.csv", parse_dates=["date"])
    trades = pd.read_csv(bt_dir / "momentum_trades.csv", parse_dates=["date"])
    days = (eq["date"].iloc[-1] - eq["date"].iloc[0]).days
    yrs = days / 365.25 if days > 0 else 1
    rt = trades[trades["side"] == "SELL"] if "side" in trades.columns else trades
    rt_per_year = len(rt) / yrs if yrs > 0 else 0

    rets = eq["portfolio_value"].astype(float).pct_change().dropna()
    ann_vol = float(rets.std() * math.sqrt(252)) if len(rets) > 1 else None
    cagr = m.get("cagr")
    dd = m.get("max_drawdown")
    # Sharpe with rf=5%, matching the convention in CLAUDE.md and OM25 v3
    sharpe = ((cagr - 0.05) / ann_vol
              if cagr is not None and ann_vol and ann_vol > 0 else None)
    # Sortino: rf=5%, downside-only vol
    downside = rets[rets < 0]
    if len(downside) > 1 and downside.std() > 0:
        sortino = float((rets.mean() * 252 - 0.05) /
                        (downside.std() * math.sqrt(252)))
    else:
        sortino = None
    calmar = (cagr / abs(dd)) if (cagr is not None and dd not in (None, 0)
                                   and abs(dd) > 1e-6) else None

    return {
        "track": label,
        "lookback_m": lb, "skip_days": skip, "vol_floor": vf,
        "vol_power": vp, "exit_buffer": buf,
        "cagr_pct": round(cagr * 100, 2) if cagr is not None else None,
        "sharpe": round(sharpe, 2) if sharpe is not None else None,
        "sortino": round(sortino, 2) if sortino is not None else None,
        "max_dd_pct": round(dd * 100, 2) if dd is not None else None,
        "calmar": round(calmar, 2) if calmar is not None else None,
        "total_return_pct": round(m.get("total_return", 0) * 100, 2),
        "vol_pct": round(ann_vol * 100, 2) if ann_vol else None,
        "hit_rate": round(m.get("hit_rate_overall", 0) * 100, 1),
        "rt_per_year": round(rt_per_year, 1),
        "n_trades": int(m.get("trades_total", 0)),
        "start": str(eq["date"].iloc[0].date()),
        "end": str(eq["date"].iloc[-1].date()),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--prices-dir", type=Path,
                    default=ROOT / "nse500_data",
                    help="Use nse500_data for production-window apples-to-apples; "
                         "nse500_data_merged for full 2009+ history.")
    ap.add_argument("--universe-file", type=Path,
                    default=ROOT / "data/static/nse500_universe.csv")
    ap.add_argument("--work-dir", type=Path, default=Path("/tmp/mm_legacy"))
    ap.add_argument("--output", type=Path,
                    default=ROOT / "tasks/MM-tuning/legacy_compare.csv")
    args = ap.parse_args()

    args.work_dir.mkdir(parents=True, exist_ok=True)

    rows = []
    for label, lb, skip, vf, vp, buf in CONFIGS:
        print(f"\n[run] {label}", flush=True)
        try:
            row = run_one(label, lb, skip, vf, vp, buf,
                          args.prices_dir, args.universe_file, args.work_dir)
        except Exception as e:
            print(f"  FAILED: {e}", file=sys.stderr)
            continue
        rows.append(row)
        print(f"  done — CAGR={row['cagr_pct']}%  Sharpe={row['sharpe']}  "
              f"DD={row['max_dd_pct']}%  Calmar={row['calmar']}  "
              f"RT/yr={row['rt_per_year']}", flush=True)

    df = pd.DataFrame(rows)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(args.output, index=False)

    print(f"\n{'=' * 110}")
    print(f"LEGACY ENGINE — Production-window comparison ({args.prices_dir.name})")
    print(f"  Live production claim (CLAUDE.md): CAGR 59.4% / Sharpe 1.92 / MaxDD -30.0%")
    print(f"{'=' * 110}")
    show = ["track", "cagr_pct", "sharpe", "sortino", "max_dd_pct", "calmar",
            "vol_pct", "hit_rate", "rt_per_year", "start", "end"]
    print(df[show].to_string(index=False))
    print(f"\n[wrote] {args.output}")


if __name__ == "__main__":
    main()
