export const metadata = {
  title: "Disclaimer — Marketworks",
};

export default function DisclaimerPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-12 prose prose-neutral dark:prose-invert">
      <h1>Investment Disclaimer</h1>

      <p className="text-sm text-muted-foreground">
        Last updated: <strong>placeholder — to be filled before public launch</strong>
      </p>

      <h2>Not investment advice</h2>
      <p>
        Marketworks publishes <strong>model portfolios</strong> generated by
        rules-based quantitative strategies for educational and research
        purposes only. Nothing on this site constitutes investment advice,
        a solicitation, or a recommendation to buy or sell any security.
      </p>

      <h2>No broker linkage</h2>
      <p>
        Marketworks does not place trades on your behalf and does not connect
        to your brokerage account. Any decision to act on the model portfolios
        is solely your own and executed entirely through your own broker.
      </p>

      <h2>Past performance ≠ future returns</h2>
      <p>
        Historical backtest results shown on the platform are derived from
        published data and our own strategy implementations. They are not
        guarantees of future performance. The Indian equity market is
        volatile; loss of capital is possible and probable in adverse
        periods.
      </p>

      <h2>Regulatory position</h2>
      <p>
        Marketworks is currently <strong>not registered with SEBI</strong> as
        either a Research Analyst or an Investment Adviser. Our regulatory
        position is under review prior to any public launch. By using the
        platform today you acknowledge that the published model portfolios
        are research outputs, not regulated advice.
      </p>

      <h2>Your responsibility</h2>
      <p>
        You are responsible for evaluating each model portfolio against your
        own financial situation, risk tolerance, and tax position. Consider
        consulting a SEBI-registered investment adviser before acting on any
        portfolio decision.
      </p>

      <p className="text-sm text-muted-foreground">
        This page is a placeholder. Final disclaimer copy will be
        prepared with legal review before public launch.
      </p>
    </div>
  );
}
